plot:
  Rectangle: True
  Corner Points: True
  Planes: True
  Intersections: True
  Bends: False
  Bending Points: True
  Flange: True
  Quads: True

  point_size: 20
  font_size: 30

  planeA_color: "#EC11E5"
  planeB_color: "#F0AC53"
  
  BP1_color: "red"
  BP2_color: "blue"
  
  FPA1_color: "green"
  FPA2_color: "green"
  FPB1_color: "orange"
  FPB2_color: "orange"

  debug_labels: True   # toggle labels for bends, BPs, tabs, planes

3D: True
2D: False